// lib/firebase_options.dart
// This file is generated by FlutterFire CLI.
// Run: flutterfire configure
// Then replace this file with the generated one.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIG

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVK6D-dWwsuYjKmOnBBWOxO6TzlfusymQ',
    appId: '1:302175322564:web:8b5f9e77ba4196a726e491',
    messagingSenderId: '302175322564',
    projectId: 'fitpulse-26be3',
    authDomain: 'fitpulse-26be3.firebaseapp.com',
    storageBucket: 'fitpulse-26be3.firebasestorage.app',
    measurementId: 'G-J907EJT1VF',
  );

  // Get these values from: Firebase Console > Project Settings > General > Your apps

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG3k1X_GF1FYdNRiRIbShFDMbNX2qLMCM',
    appId: '1:302175322564:android:f1eabf481678732b26e491',
    messagingSenderId: '302175322564',
    projectId: 'fitpulse-26be3',
    storageBucket: 'fitpulse-26be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.yourcompany.fitpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.yourcompany.fitpulse',
  );
}